name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: |
        ssh ubuntu@<IP_ADDRESS> 'sudo apt-get update && sudo apt-get install git nginx php8.1-fpm php-common php-cli php-mbstring php-xml php-zip -y'
      env:
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}

    - name: Install composer
      run: |
        ssh ubuntu@<IP_ADDRESS> 'sudo curl -sS https://getcomposer.org/installer -o composer-setup.php'
        ssh ubuntu@<IP_ADDRESS> 'sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer'
      env:
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}

    
    - name: Deploy code
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
        --exclude='vendor' --exclude='node_modules' --exclude='.git' \
        --exclude='.github' --exclude='storage' \
        .  ubuntu@<IP_ADDRESS>:/var/www/laravel
      env:
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}

    - name: Install PHP dependencies
      run: |
        ssh ubuntu@<IP_ADDRESS> 'cd /var/www/laravel && composer install'
      env:
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}

    - name: Configure Nginx
      run: |
        ssh ubuntu@<IP_ADDRESS> 'sudo rm /etc/nginx/sites-available/default'
        ssh ubuntu@<IP_ADDRESS> 'sudo touch /etc/nginx/sites-available/default'
        ssh ubuntu@<IP_ADDRESS> 'sudo echo "server {
                listen 80;
                listen [::]:80;
                server_name <DOMAIN_NAME>;
                root /var/www/laravel/public;
                index index.php index.html index.htm;
                location / {
                    try_files $uri $uri/ /index.php$is_args$args;
                }
                location ~ \.php$ {
                    fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
                    include snippets/fastcgi-php.conf;
                }
            }" > /etc/nginx/sites-available/default'
