name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
        --exclude='vendor' --exclude='node_modules' --exclude='.git' \
        --exclude='.github' --exclude='storage' \
        .  example@<IP_ADDRESS>:/var/www/laravel
      env:
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}

    - name: Install dependencies
      run: |
        ssh example@<IP_ADDRESS> 'cd /var/www/laravel && composer install'
      env:
        IP_ADDRESS: ${{ secrets.IP_ADDRESS }}

    - name: Configure Nginx
      run: |
        ssh example@<IP_ADDRESS> 'sudo apt-get update && sudo apt-get install nginx -y'
        ssh example@<IP_ADDRESS> 'sudo rm /etc/nginx/sites-available/default'
        ssh example@<IP_ADDRESS> 'sudo touch /etc/nginx/sites-available/default'
        ssh example@<IP_ADDRESS> 'sudo echo "server {
                listen 80;
                listen [::]:80;
                root /var/www/laravel/public;
                index index.php index.html index.htm;
                server_name _;
                location / {
                        try_files \$uri \$uri/ /index.php?\$query_string;
                }
                location ~ \.php$ {
                        include snippets/fastcgi-php.conf;
                        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
                }
                location ~ /\.ht {
                        deny all;
                }
        }" > /etc/nginx/sites-available/default'
        ssh example@<IP_ADDRESS> 'sudo systemctl restart
